name: dio_api_kit
description: A lightweight, backend-agnostic API layer built on top of Dio with configurable success handling, centralized error management, and clean architecture support.
version: 1.0.1

homepage: https://github.com/ASHISH1317/dio_api_kit
repository: https://github.com/ASHISH1317/dio_api_kit
issue_tracker: https://github.com/ASHISH1317/dio_api_kit/issues
license: MIT

topics:
  - dio
  - networking
  - api
  - http
  - clean-architecture

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
